- name: Redis Container
  community.docker.docker_container:
    name: "{{ redis.host }}"
    image: "{{ redis.image }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker.network_name }}"
    published_ports:
      - "{{ redis.port }}:{{ redis.port }}"
