- name: Force update betest backend repository
  shell: |
    if [ -d /home/ubuntu/14-YG-BE ]; then
      cd /home/ubuntu/14-YG-BE && git fetch origin && git checkout -B main origin/main
    else
      git clone -b main https://github.com/100-hours-a-week/14-YG-BE.git /home/ubuntu/14-YG-BE
    fi
  args:
    executable: /bin/bash

- name: Mark betest repo as safe for git
  shell: git config --global --add safe.directory /home/ubuntu/14-YG-BE
  become: false
  args:
    executable: /bin/bash

- name: Load backend-specific variables
  include_vars:
    file: "{{ playbook_dir }}/group_vars/be_var.yml"

- name: Generate .env.prod file from template
  template:
    src: env.prod.j2
    dest: /home/ubuntu/14-YG-BE/.env.prod
    mode: "0644"
    owner: ubuntu
    group: ubuntu

- name: Build betest backend project
  shell: ./gradlew clean bootJar -x test
  args:
    chdir: /home/ubuntu/14-YG-BE

- name: Stop existing betest backend application
  shell: |
    pkill -f '14-YG-BE' || true
  ignore_errors: true

- name: Deploy Spring Boot backend systemd service
  template:
    src: spring_backend.service.j2
    dest: /etc/systemd/system/spring_backend.service
  become: true

- name: Reload systemd to recognize Spring Boot service
  systemd:
    daemon_reload: yes
  become: true

- name: Enable and start Spring Boot service
  systemd:
    name: spring_backend
    enabled: yes
    state: started
  become: true

#- name: Backup built betest backend jar if health check passes
#  shell: |
#    JAR_PATH=$(find /home/ubuntu/14-YG-BE/build/libs -name '*.jar' | head -n 1)
#    cp "$JAR_PATH" "$JAR_PATH.bak"
#  when: be_moongsan_health.status == 200
#  args:
#    executable: /bin/bash

- name: Ensure logrotate config for betest backend exists
  copy:
    dest: /etc/logrotate.d/be_moongsan
    content: |
      /home/ubuntu/logs/be_moongsan.log {
          weekly
          rotate 4
          compress
          delaycompress
          missingok
          notifempty
          create 0644 ubuntu ubuntu
      }
  become: true
