# apt 패키지 설치
- name: Run apt update (once)
  apt:
    name:
      - nginx
      - certbot
      - python3-certbot-nginx
      - mysql-client
      - git
      - curl
      - unzip
    state: present
    update_cache: yes
  retries: 5
  delay: 15
  register: result
  until: result is succeeded
  become: true

# docker 공식 스크립트로 설치
- name: Install Docker using official script
  shell: curl -fsSL https://get.docker.com | sh
  args:
    executable: /bin/bash
  become: true

# logs 디렉토리 생성
- name: Ensure logs directory exists
  file:
    path: /home/ubuntu/logs
    state: directory
    mode: "0755"
    owner: ubuntu
    group: ubuntu

# 디스크 정리 작업 추가
- name: Clean up APT cache and remove unused packages
  apt:
    autoclean: yes
    autoremove: yes
  become: true

- name: Remove downloaded Chrome .deb file
  file:
    path: /tmp/google-chrome.deb
    state: absent
  become: true

- name: Ensure /tmp directory permissions are secure
  file:
    path: /tmp
    state: directory
    mode: "1777"
  become: true

- name: Clean up old journal logs (older than 3 days)
  command: journalctl --vacuum-time=3d
  become: true
  failed_when: false
  ignore_errors: yes

# Docker 데몬 & 권한 확인
# •	ubuntu 유저를 docker 그룹에 포함시켜야 non-root 실행 가능
# •	재부팅 없이 적용하려면 newgrp docker 또는 로그아웃/로그인 필요
- name: Add ubuntu user to docker group
  user:
    name: ubuntu
    groups: docker
    append: yes
  become: true
# 이후 newgrp docker 직접 실행하거나, 재부팅 후 적용
