- name: Clone 14-YG-CLOUD repository
  git:
    repo: "{{ project_repos.cloud_url }}"
    dest: "{{ project_paths.cloud_repo }}"
    version: "{{ project_repos.cloud_branch }}"
    force: yes
  when: "'backend' in group_names or 'ai' in group_names"
