- name: Convert MySQL root user to mysql_native_password
  shell: |
    mysql -u root <<EOF
    ALTER USER 'root'@'localhost' IDENTIFIED WITH mysql_native_password BY '{{ db_root_password }}';
    FLUSH PRIVILEGES;
    EOF
  become: true

- name: Ensure MySQL server is installed (fail-safe)
  apt:
    name: mysql-server
    state: present
    update_cache: yes
  become: true

- name: Create database
  community.mysql.mysql_db:
    name: "{{ db_name }}"
    state: present
    encoding: utf8mb4
    collation: utf8mb4_general_ci
    login_user: "{{ db_root_user }}"
    login_password: "{{ db_root_password }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Create database user and grant privileges
  community.mysql.mysql_user:
    name: "{{ db_user }}"
    password: "{{ db_password }}"
    priv: "{{ db_name }}.*:ALL"
    host: localhost
    state: present
    login_user: "{{ db_root_user }}"
    login_password: "{{ db_root_password }}"
  vars:
    ansible_python_interpreter: /usr/bin/python3

- name: Set system timezone to Asia/Seoul
  command: timedatectl set-timezone Asia/Seoul
  when: ansible_date_time.tz != "KST"

- name: Set MySQL default timezone
  lineinfile:
    path: /etc/mysql/mysql.conf.d/mysqld.cnf
    regexp: "^default-time-zone"
    line: 'default-time-zone = "+09:00"'
    insertafter: "[mysqld]"

- name: Restart MySQL
  service:
    name: mysql
    state: restarted
