version: "3.9"

services:
  backend:
    build:
      context: ./backend
    container_name: spring_backend
    ports:
      - "8080:8080"
    env_file:
      - /home/ubuntu/envs/{{ group_names[0] }}/backend.env.prod
    restart: unless-stopped # 컨테이너가 종료되면 자동으로 재시작

  ai:
    build:
      context: ./ai # AI 서버
    container_name: fastapi_ai # AI 서버
    ports:
      - "8100:8100" # AI 서버 포트
    env_file:
      - /home/ubuntu/envs/{{ group_names[0] }}/ai.env.prod
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend
    env_file:
      - /home/ubuntu/envs/{{ group_names[0] }}/frontend.env.prod
    restart: unless-stopped
    volumes:
      - /home/ubuntu/14-YG-FE/dist:/var/www/react
    # frontend는 포트 노출 X → nginx가 직접 서빙
