- name: Ensure Docker network {{ docker.network_name }} exists
  community.docker.docker_network:
    name: "{{ docker.network_name }}"
    driver: "{{ docker.network_driver }}"
    ipam_config:
      - subnet: "{{ docker.network_subnet }}"
    state: present
  become: true
