- name: Check if DB dump file exists
  stat:
    path: "/home/{{ system.user }}/dump.sql"
  register: db_dump_stat

- name: Upload DB dump file
  copy:
    src: "./files/dump.sql"
    dest: "/home/{{ system.user }}/dump.sql"
    mode: "0644"
    owner: "{{ system.user }}"
    group: "{{ system.user }}"

- name: Recheck if DB dump file exists
  stat:
    path: "/home/{{ system.user }}/dump.sql"
  register: db_dump_stat # 덮어쓰기

- name: Restore DB from dump
  shell: >
    docker exec -i mysql-{{ service_name }} mysql 
    -u {{ db.mysql.user }} -p'{{ db.mysql.password }}' 
    {{ db.mysql.name }} < /home/{{ system.user }}/dump.sql
  when: db_dump_stat.stat.exists

- name: Remove dump file after import
  file:
    path: "/home/{{ system.user }}/dump.sql"
    state: absent
  when: db_dump_stat.stat.exists
