- name: Mongo Container
  community.docker.docker_container:
    name: "{{ db.mongo.container_name }}"
    image: "{{ db.mongo.image }}:{{ db.mongo.tag }}"
    state: started
    restart_policy: always
    networks:
      - name: "{{ docker.network_name }}"
    published_ports:
      - "{{ db.mongo.port }}:{{ db.mongo.port }}"
