- name: "Debug BE Deploy"
  hosts: backend
  become: yes
  gather_facts: yes
  vars:
    env: test

  tasks:
    - name: "Debug variables"
      debug:
        msg: |
          Environment: {{ env }}
          Group names: {{ group_names }}
          Service name: {{ service_name | default('undefined') }}

    - name: "Execute BE Deploy Role"
      include_role:
        name: be_deploy
