# Development Environment Inventory
# 단일 서버 구조

[dev]
dev.moongsan.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/lsh-study-key

# 변수 설정
[dev:vars]
env=dev
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
service_name=moongsan
