- name: Setup Production Server
  hosts: prod
  become: yes
  roles:
    - {role: common, tags: common} # 공통 패키지 설치 sudo apt update & install
    - {role: monitoring, tags: monitoring} # 모니터링 패키지 설치
    - {role: database, tags: database} # db
    - {role: nginx_conf, tags: nginx_conf} # nginx conf
    # - {role: fastapi, tags: fastapi}
    - {role: aitest, tags: fastapi} # fastapi
    # - {role: backend, tags: backend}
    - {role: betest, tags: backend} # pr됐습니다~ -> 이거 실행 -> 배포되는지 확인
    # - {role: frontend, tags: frontend}
    - {role: fetest, tags: frontend} # pr됐습니다~ -> 이거 실행 -> 배포되는지 확인
    - {role: db_backup, tags: db_backup} # db backup
- name: Setup test Server
  hosts: test
  become: yes
  roles:
    - {role: common, tags: common} # 공통 패키지 설치 sudo apt update & install
    - {role: clone_cloud, tags: clone_cloud} # 클라우드 서버에서만 실행
    - {role: betest, tags: backend} # pr됐습니다~ -> 이거 실행 -> 배포되는지 확인
