# Production Environment Inventory
# 단일 서버 구조

[prod]
moongsan.com ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/lsh-study-key

# 변수 설정
[prod:vars]
env=prod
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
service_name=moongsan
