# Shared Infrastructure Inventory
# WireGuard VPN 서버 및 공유 인프라

[shared:children]
elk_servers
jenkins_servers

[shared]
shared-jumpbox ansible_host=34.22.110.81 ansible_user=lsh ansible_ssh_private_key_file=~/.ssh/lsh-study-key

[elk_servers]
shared-elk ansible_host=34.47.84.135 ansible_user=lsh ansible_ssh_private_key_file=~/.ssh/lsh-study-key
aws-shared-elk ansible_host=43.203.65.98 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/lsh/.ssh/id_ed25519

[jenkins_servers]
aws-shared-jenkins ansible_host=3.38.150.190 ansible_user=ubuntu ansible_ssh_private_key_file=/Users/lsh/.ssh/id_ed25519

# 변수 설정
[shared:vars]
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
env=shared